// The reel: the film's whole soundtrack, rendered offline from the very cues the sim judges you
// against, so what you hear is exactly what hides you. Three kinds of stem, started together:
//   screen  - the film itself, out of the speakers behind the screen (stereo)
//   crowd   - the whole room reacting: laughs, screams, applause (stereo, played into the room)
//   local   - one mono stem per person who makes their own noise (a snorer, a whistling fan), so
//             it can be panned to their seat and faded out the moment they go quiet
import { E, db, gain, filt, noiseBuf, impulse, chain } from './core.js';
import { levelAt } from '../film.js';
import { mulberry32 } from '../util.js';
import { WORLD } from './world.js';
import { SCORE } from './score.js';
import { CROWD } from './crowd.js';
import { TRIM } from './trim.js';

// loudness mapping: a cue at L dB (at 1 m) plays rel(L) dB above its voice's unit loudness (UNIT
// LUFS, measured over 10 ms blocks). Half a dB per dB keeps a cinema's 60 dB of range inside a
// laptop's; above KNEE it gets gentler still, so explosions are huge without tearing the speakers.
export const REF = 60, SLOPE = 0.5, KNEE = 78, SLOPE2 = 0.3, UNIT = -25;
export const rel = (L) => (L <= KNEE ? (L - REF) * SLOPE : (KNEE - REF) * SLOPE + (L - KNEE) * SLOPE2);
export const amp = (L) => (L === -Infinity ? 0 : db(rel(L)));
export const TAIL = 2.5;                       // s of ring-out after the film's last second

export const VOICES = { ...WORLD, ...SCORE, ...CROWD };
// how much of each voice goes to the film's own hall: the score was recorded on a scoring stage,
// foley and dialogue close. The audience needs none, nor does anyone in it: they are in the cinema with you.
const HALL = { score: 0.34, world: 0.1, line: 0.07, crowd: 0 };
const hallOf = (cue) => (cue.src ? 0 : cue.id ? HALL.line : CROWD[cue.k] ? HALL.crowd : SCORE[cue.k] ? HALL.score : HALL.world);
const irCache = new Map();
function hallIR(c) {
  const k = c.sampleRate + ':' + c.destination.channelCount;
  if (!irCache.has(k)) irCache.set(k, impulse(c, 2.6, 2.7, { pre: 0.024, dark: 0.62, seed: 91, early: [[0.019, 0.24], [0.031, 0.19], [0.047, 0.14], [0.066, 0.1]] }));
  return irCache.get(k);
}
export const CROWDK = new Set(Object.keys(CROWD));
// TRIM (generated by tools/audio_test.mjs): each voice's measured loudness above UNIT, by
// 'film:kind#n' (one cue), 'film:kind' or 'kind', so every cue sits exactly where its level says
export { TRIM };
export const trimOf = (id, cue) => {
  if (cue.id) return TRIM[`${id}:line:${cue.id}@${E.lang}`] ?? TRIM[`${id}:line:${cue.id}`] ?? TRIM[cue.src ? 'pline' : 'line'] ?? 0;
  return TRIM[`${id}:${cue.k}#${cue.n_ ?? -1}`] ?? TRIM[`${id}:${cue.k}`] ?? TRIM[cue.k] ?? 0;
};
// number every cue within its kind (n_), the stable half of a TRIM key: times move with the
// language's line lengths, but the third thunderclap is always the third
export function number(film) {
  if (film._numbered) return film;
  const seen = {};
  for (const c of film.cues) if (!c.id) c.n_ = (seen[c.k] = (seen[c.k] ?? -1) + 1);
  film._numbered = true;
  return film;
}

// ---- procedural textures: dense grain clouds computed once in JS instead of thousands of nodes ----
const texCache = new Map();
function texture(c, name, sec, fn, ch = 2) {
  const key = name + '@' + c.sampleRate;
  if (texCache.has(key)) return texCache.get(key);
  const sr = c.sampleRate, n = Math.floor(sec * sr), b = c.createBuffer(ch, n, sr), rnd = mulberry32(name.length * 7919 + 17);
  for (let k = 0; k < ch; k++) fn(b.getChannelData(k), sr, rnd, k);
  texCache.set(key, b);
  return b;
}
// a decaying two-pole resonance struck at i0: the grain everything below is made of
function ping(d, i0, f, decay, a, sr, q = 0) {
  const w = 2 * Math.PI * f / sr, r = Math.exp(-1 / (decay * sr)), c1 = 2 * r * Math.cos(w), c2 = -r * r;
  let y1 = 0, y2 = 0; const n = Math.min(d.length - i0, Math.ceil(decay * sr * 7));
  for (let i = 0; i < n; i++) { const x = i === 0 ? a : i < 3 && q ? a * q : 0, y = x + c1 * y1 + c2 * y2; y2 = y1; y1 = y; d[i0 + i] += y * (1 - r); }
}
export const TEX = {
  drops: (c) => texture(c, 'drops', 3.1, (d, sr, rnd) => { for (let t = 0; t < 3.1; t += -Math.log(1 - rnd()) / 60) ping(d, Math.floor(t * sr), 1400 + rnd() * rnd() * 6000, 0.002 + rnd() * 0.006, (0.3 + rnd()) * 2.2, sr); }),
  crackle: (c) => texture(c, 'crackle', 2.3, (d, sr, rnd) => { for (let t = 0; t < 2.3; t += -Math.log(1 - rnd()) / 90) { const i = Math.floor(t * sr), a = Math.pow(rnd(), 3) * 0.9; d[i] += a; if (i + 1 < d.length) d[i + 1] -= a * 0.6; } }),
  claps: (c) => texture(c, 'claps', 4.3, (d, sr, rnd) => {
    for (let t = 0; t < 4.3; t += -Math.log(1 - rnd()) / 70) {
      const i0 = Math.floor(t * sr), f = 900 + rnd() * 1700, amp = 0.35 + rnd() * 0.65, len = Math.floor((0.008 + rnd() * 0.01) * sr);
      for (let fl = 0; fl < 2; fl++) { const j0 = i0 + Math.floor(fl * 0.004 * sr * rnd()); let lp = 0; for (let i = 0; i < len && j0 + i < d.length; i++) { lp += 0.5 * ((rnd() * 2 - 1) - lp); d[j0 + i] += lp * amp * Math.exp(-i / (len * 0.25)) * (fl ? 1 : 0.5); } }
      ping(d, i0, f, 0.003, amp * 0.6, sr);
    }
  }),
  crickets: (c) => texture(c, 'crickets', 5.3, (d, sr, rnd, ch) => {
    for (let k = 0; k < 3; k++) {
      const f = 4300 + k * 380 + ch * 90, per = 0.36 + k * 0.11;
      for (let t = rnd() * per; t < 5.2; t += per * (0.9 + rnd() * 0.2)) for (let p = 0; p < 3 + (k & 1); p++) ping(d, Math.floor((t + p * 0.022) * sr), f, 0.004, 0.5 * (k === ch ? 1 : 0.45), sr);
    }
  }),
};

// swap the audio engine onto an offline context while a render is being scheduled
export function offline(c, seed, fn) {
  const keep = { ctx: E.ctx, nz: E.nz, offline: E.offline, rnd: E.rnd, clock: E.clock };
  E.ctx = c; E.offline = true; E.clock = 0; E.rnd = mulberry32(seed);
  if (!E._nzOff || E._nzOff.sr !== c.sampleRate) E._nzOff = { sr: c.sampleRate, white: noiseBuf(c, 2, 'white', 11), pink: noiseBuf(c, 3, 'pink', 23), brown: noiseBuf(c, 4, 'brown', 37) };
  E.nz = E._nzOff;
  try { return fn(); } finally { Object.assign(E, keep); }
}

// the cue's loudness curve as gain automation (relative to the voice's unit level)
function automate(c, cue, g, t0, t1, trimDb) {
  const span = Math.max(0.01, t1 - t0), rate = span < 2.5 ? 1000 : 200, n = Math.max(2, Math.ceil(span * rate) + 1);
  const a = new Float32Array(n), trim = db(-trimDb);
  for (let i = 0; i < n; i++) a[i] = amp(levelAt(cue, t0 + (i / (n - 1)) * span)) * trim;
  g.gain.setValueAtTime(a[0], t0);
  g.gain.setValueCurveAtTime(a, t0, span);
  g.gain.setValueAtTime(0, t0 + span + 0.001);
}

// a spoken line from the voice manifest; the film's own voices come out of the screen speakers
function speak(cue, x) {
  const b = x.buf(cue.id); if (!b) return;
  const s = x.ctx.createBufferSource(); s.buffer = b;
  if (cue.src) s.connect(x.dest);
  else s.connect(filt(x.ctx, 'highpass', 95, 0.7)).connect(x.dest);
  s.start(cue.t); s.stop(Math.min(x.t1, cue.t + b.duration + 0.05));
}

const fnv = (str) => { let h = 2166136261; for (let i = 0; i < str.length; i++) h = Math.imul(h ^ str.charCodeAt(i), 16777619); return h >>> 0; };

function place(cue, x, out, dur) {
  const V = cue.id ? speak : VOICES[cue.k];
  if (!V) { console.warn('[reel] no voice for', cue.k); return; }
  const t0 = cue.t, t1 = Math.min(cue.end, dur);
  if (t1 <= t0) return;
  const g = gain(x.ctx, 0); g.connect(out);
  const send = hallOf(cue); if (send && x.hall) chain(g, gain(x.ctx, send), x.hall);
  automate(x.ctx, cue, g, t0, t1, x.trim ? x.trim(cue) : trimOf(x.meta.id, cue));
  const last = cue.pts[cue.pts.length - 1][0];
  // every cue draws from its own seeded stream, so it sounds the same alone (tests), in any
  // grouping of parallel renders and in either language
  const rnd = mulberry32(fnv(`${x.meta.id}:${cue.id || cue.k + '#' + cue.n_}`));
  E.rnd = rnd;
  V(cue, { ...x, rnd, dest: g, t0, t1, hold: cue.t + last, len: last });
}

// render one stem; cues is the subset of the film that belongs to it. o.until cuts the render
// short (tests measuring one cue); o.trim(cue) overrides the TRIM table
function stem(level, film, cues, ch, o) {
  const OAC = globalThis.OfflineAudioContext || globalThis.webkitOfflineAudioContext;
  const dur = film.dur + TAIL, sr = o.sr || 44100, len = Math.min(dur, o.until ?? dur);
  const c = new OAC(ch, Math.ceil(len * sr), sr);
  number(film);
  offline(c, 1, () => {
    const out = gain(c, 1); out.connect(c.destination);
    const hall = c.createConvolver(); hall.buffer = hallIR(c); hall.normalize = true;
    const hin = gain(c, 1); chain(hin, hall, out);
    const x = { hall: hin, ctx: c, film, meta: level.meta, B: level.meta.bpm ? 60 / level.meta.bpm : 0.5, buf: o.buf, dur, TEX, trim: o.trim };
    for (const cue of cues) place(cue, x, out, dur);
  });
  return c.startRendering();
}
// any subset of a film's cues, alone (tests)
export function renderCues(level, film, cues, o = {}) {
  return stem(level, film, cues, o.ch || 2, { ...o, buf: o.buf || ((id) => E.buf(id)) });
}

// rough render cost of each voice (ms per second of cue, tools/audio_test prof), to balance the
// screen stem over several contexts rendering at once
const COST = { swing: 650, applause: 400, piano: 200, theme: 185, orchestra: 165, strings: 135, whisper: 85, crowdscream: 80, train: 40, laugh: 40, rotor: 36, musicbox: 32, stinger: 30, score: 30 };
const cost = (c, dur) => (c.id ? 3 : COST[c.k] ?? 6) * (Math.min(c.end, dur) - c.t) + 4;
function split(cues, k, dur) {
  const g = Array.from({ length: Math.max(1, k) }, () => ({ w: 0, cues: [] }));
  for (const c of cues.slice().sort((a, b) => cost(b, dur) - cost(a, dur))) { const m = g.reduce((a, b) => (b.w < a.w ? b : a)); m.cues.push(c); m.w += cost(c, dur); }
  const out = g.filter((x) => x.cues.length).map((x) => x.cues);
  return out.length ? out : [[]];
}
function sum(bufs) {
  const [a, ...rest] = bufs;
  for (const b of rest) for (let c = 0; c < a.numberOfChannels; c++) { const d = a.getChannelData(c), e = b.getChannelData(c); for (let i = 0; i < d.length; i++) d[i] += e[i]; }
  return a;
}

// A look-ahead brickwall limiter that adds no delay: the gain starts dipping a couple of ms before
// each peak arrives, so the ceiling is exact and nothing shifts against the sim's clock.
// Returns the most gain reduction applied (dB). Explosions keep their size; speakers keep headroom.
export function limit(buf, ceilDb = -1, relS = 0.08, lookS = 0.002) {
  const n = buf.length, sr = buf.sampleRate, ch = buf.numberOfChannels, L = Math.max(1, Math.round(lookS * sr)), ceil = Math.pow(10, ceilDb / 20);
  const D = []; for (let c = 0; c < ch; c++) D.push(buf.getChannelData(c));
  const req = new Float32Array(n); let any = false;
  for (let i = 0; i < n; i++) { let p = 0; for (let c = 0; c < ch; c++) { const v = Math.abs(D[c][i]); if (v > p) p = v; } if (p > ceil) { req[i] = ceil / p; any = true; } else req[i] = 1; }
  if (!any) return 0;
  const m = new Float32Array(n), q = new Int32Array(n); let h = 0, t = 0;
  for (let i = n - 1; i >= 0; i--) {                      // m[i] = min(req[i .. i+L]), monotonic deque
    while (t > h && req[q[t - 1]] >= req[i]) t--;
    q[t++] = i;
    while (q[h] > i + L) h++;
    m[i] = req[q[h]];
  }
  const a = 1 - Math.exp(-1 / (relS * sr)); let acc = 0, r = 1, lo = 1;
  for (let i = 0; i < n; i++) {
    acc += m[i]; if (i > L) acc -= m[i - L - 1];
    const g = acc / Math.min(i + 1, L + 1);                // every sample in the box looked ahead past i
    r = g < r ? g : r + (g - r) * a;
    if (r < lo) lo = r;
    for (let c = 0; c < ch; c++) D[c][i] *= r;
  }
  return -20 * Math.log10(lo);
}

// ---- what the reel really sounds like, for the sim ----
// K-weighting (BS.1770, approximately): the ear's own EQ, so a rumble and a whistle compare fairly
export async function kweight(buf) {
  const OAC = globalThis.OfflineAudioContext || globalThis.webkitOfflineAudioContext;
  const c = new OAC(buf.numberOfChannels, buf.length, buf.sampleRate), s = c.createBufferSource(); s.buffer = buf;
  const hs = c.createBiquadFilter(); hs.type = 'highshelf'; hs.frequency.value = 1500; hs.gain.value = 4;
  const hp = c.createBiquadFilter(); hp.type = 'highpass'; hp.frequency.value = 38; hp.Q.value = 0.5;
  s.connect(hs).connect(hp).connect(c.destination); s.start(0);
  return c.startRendering();
}
// loudness (LUFS-ish) back to the film's dB: the exact inverse of rel()
export const fromLoud = (lu) => { const r = lu - UNIT, k = rel(KNEE); return r <= k ? REF + r / SLOPE : KNEE + (r - k) / SLOPE2; };
export const ENV_HZ = 100, ENV_BACK = 0.04, ENV_AHEAD = 0.01;
// Loudness envelope of some stems heard together (their powers add), in film dB, ENV_HZ a second.
// Each value integrates the 50 ms that end 10 ms after it: the ear integrates what just happened.
export async function envelope(bufs, dur) {
  const n = Math.ceil(dur * ENV_HZ) + 1, pow = new Float64Array(n);
  for (const b of bufs) {
    if (!b) continue;
    const k = await kweight(b), sr = k.sampleRate, B = sr / ENV_HZ, nb = Math.ceil(k.length / B), blk = new Float64Array(nb + 8);
    for (let c = 0; c < k.numberOfChannels; c++) { const d = k.getChannelData(c); for (let i = 0; i < d.length; i++) blk[Math.floor(i / B)] += d[i] * d[i]; }
    const back = Math.round(ENV_BACK * ENV_HZ), ahead = Math.round(ENV_AHEAD * ENV_HZ), W = (back + ahead) * B;
    for (let j = 0; j < n; j++) { let z = 0; for (let q = j - back; q < j + ahead; q++) if (q >= 0 && q < nb) z += blk[q]; pow[j] += z / W; }
  }
  const out = new Float32Array(n);
  for (let j = 0; j < n; j++) { const L = pow[j] > 1e-13 ? fromLoud(-0.691 + 10 * Math.log10(pow[j])) : -Infinity; out[j] = L < 10 ? -Infinity : L; }
  return out;
}
// the envelopes a Film hears: the whole room (screen + audience) and each local source at 1 m
export async function envelopes(r) {
  const local = {};
  for (const [s, b] of Object.entries(r.local)) local[s] = await envelope([b], r.dur);
  return { hz: ENV_HZ, global: await envelope([r.screen, r.crowd], r.dur), local };
}

// what a reel is built from: if this changes, a bounced reel no longer matches its film
export const REEL_VERSION = 2;
const stemKey = (id, cues) => fnv([REEL_VERSION, REF, SLOPE, KNEE, SLOPE2, UNIT, TAIL].join() + JSON.stringify(cues.map((c) => [c.k, c.id, +c.t.toFixed(4), c.pts, c.rate, c.lfo, c.n, c.src, c.mood, c.muffle, trimOf(id, c)]))).toString(16).padStart(8, '0');

// the reel's parts: { screen, crowd, 'local:src' } → { cues, ch, key }. The key changes whenever
// anything that shapes the sound does (cues, timings in this language, trims, mapping)
export function parts(film, id) {
  number(film);
  const screen = film.global.filter((c) => !CROWDK.has(c.k)), crowd = film.global.filter((c) => CROWDK.has(c.k)), local = {};
  for (const c of film.local) (local[c.src] ||= []).push(c);
  const P = { screen: { cues: screen, ch: 2 }, crowd: { cues: crowd, ch: 2 } };
  for (const [s, cs] of Object.entries(local)) P['local:' + s] = { cues: cs, ch: 1 };
  for (const p of Object.values(P)) p.key = stemKey(id, p.cues);
  return P;
}

// the whole reel, rendered here and now: { screen, crowd, local: { [src]: AudioBuffer }, dur, gr }.
// o.split: how many contexts share the screen stem; o.only: render just these parts
export async function renderReel(level, film, o = {}) {
  const buf = o.buf || ((id) => E.buf(id)), opt = { ...o, buf }, dur = film.dur + TAIL, P = parts(film, level.meta.id), jobs = [];
  for (const [name, p] of Object.entries(P)) {
    if (o.only && !o.only.includes(name)) continue;
    if (!p.cues.length && name !== 'screen') continue;
    const groups = name === 'screen' ? split(p.cues, o.split ?? 4, dur) : [p.cues];
    jobs.push(Promise.all(groups.map((g) => stem(level, film, g, p.ch, opt))).then((bs) => [name, sum(bs)]));
  }
  const done = Object.fromEntries(await Promise.all(jobs)), r = { screen: done.screen || null, crowd: done.crowd || null, local: {}, dur, gr: {} };
  for (const [name, b] of Object.entries(done)) { r.gr[name] = limit(b); if (name.startsWith('local:')) r.local[name.slice(6)] = b; }
  return r;
}
