// The sharp picture inside each still (normalised x0, y0, x1, y1). Generated by tools/crops.py.
export const CROPS = {
  "f2_window":[0,0.1172,1,0.8809],
  "f2_street":[0,0.1777,1,0.832],
  "f2_letters":[0,0.0703,1,0.918],
  "f3_cat":[0,0.1055,1,0.8926],
  "f3_ghost":[0,0.154,1,0.846],
  "f3_attic":[0,0.141,1,0.859],
  "f3_doll":[0,0.1387,1,0.8574],
  "f6_keeper":[0,0.168,1,0.824],
  "f6_lever":[0,0.103,1,0.894],
  "f6_letter":[0,0.137,1,0.861],
  "f6_storm":[0,0.141,1,0.855],
  "f6_dark":[0,0.144,1,0.856],
  "f6_light":[0,0.107,1,1]
};
